language: php

php:
  - 5.6
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
# unit tests with phpunit.xml as input
- vendor/bin/phpunit
# minimal code coverage : 50% (xdebug needed)
- php coverage-checker.php clover.xml 50